/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

/**
 *
 * @author USER
 */
public class JPaneExito extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JPaneExito.class.getName());
    private String Exitomensaje;
    private Cajeroautomatico cajero;
    private Banco banco;

    /**
     * Creates new form JPaneExito
     */
    public JPaneExito(String Exitomensaje, Cuenta cuenta) {
        initComponents();
        cajero = new Cajeroautomatico(banco, 2000000);
        this.Exitomensaje = Exitomensaje;

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jOptionPane1.setMessage(this.Exitomensaje);
        jOptionPane1.setMessageType(javax.swing.JOptionPane.INFORMATION_MESSAGE);

        this.dispose();

        jOptionPane1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            @Override
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                if (evt.getPropertyName().equals(javax.swing.JOptionPane.VALUE_PROPERTY)) {
                    Object valorSeleccionado = jOptionPane1.getValue();

                    if (valorSeleccionado == null || valorSeleccionado.equals(javax.swing.JOptionPane.UNINITIALIZED_VALUE)) {
                        return;
                    }

                    if (valorSeleccionado.equals("Si")) {
                        String recibo = "Saldo actual: " + cuenta.getSaldo();
                        java.awt.EventQueue.invokeLater(() -> new JPaneRecibo(recibo).setVisible(true));
                        dispose();
                    } else if (valorSeleccionado.equals("No")) {

                        dispose();
                    }

                    jOptionPane1.setValue(javax.swing.JOptionPane.UNINITIALIZED_VALUE);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jOptionPane1.setOptions(new Object[]{"Si", "No"});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Banco bancoPrueba = new Banco("Banco Demo");
        Cliente clientePrueba = new Cliente("Ana Perez", "1001");
        bancoPrueba.agregarCliente(clientePrueba);

        Cuenta cuentaPrueba = new Cuenta("C001", clientePrueba, 500000, 400000);
        cuentaPrueba.asignarTarjeta(new Tarjeta("1111", "1234"));
        bancoPrueba.agregarCuenta(cuentaPrueba);

        Cajeroautomatico cajeroPrueba = new Cajeroautomatico(bancoPrueba, 2000000);
        Cuenta cuentaEncontrada = cajeroPrueba.buscarCuentaPorTarjeta("1111");

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JPaneExito("Exito", cuentaEncontrada).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane jOptionPane1;
    // End of variables declaration//GEN-END:variables
}
