/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

/**
 *
 * @author USER
 */
public class VistaBoletas extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(VistaBoletas.class.getName());
    private Evento btsArirang;
    private Evento humbeTour;
    private Evento megaland;

    private Banco banco;
    private Cajeroautomatico cajero;
    private String numeroTarjeta;
    private String mensaje;
    private Cuenta cuenta;

    /**
     * Creates new form VistaBoletas
     */
    public VistaBoletas(String numeroTarjeta) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.numeroTarjeta = numeroTarjeta;
        inicializarEventos();
    }

    public VistaBoletas(Cajeroautomatico cajero, String numeroTarjeta) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.cajero = cajero;
        this.numeroTarjeta = numeroTarjeta;
        inicializarEventos();
    }

    public VistaBoletas() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.numeroTarjeta = "1111"; // Valor por defecto para pruebas
        inicializarEventos();
    }

    private void inicializarEventos() {
        btsArirang = new Evento("Bts Arirang", 450000);
        humbeTour = new Evento("Humbe Esencia Tour", 275000);
        megaland = new Evento("Megaland", 150000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jLabel2.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{"Bts Arirang", "Megaland", "Humbe Esencia Tour"}));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jLabel6.setText("Eventos Disponibles");

        jLabel7.setText("Seleccione evento");

        jLabel8.setText("Precio: 450mil");

        jLabel9.setText("Precio: 275mil");

        jLabel10.setText("Precio: 150mil");

        jButton1.setText("Comprar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Regresar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel1.setText("BTS");

        jLabel11.setText("Escencia");

        jLabel12.setText("Megaland");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel8)
                                .addGap(155, 155, 155)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(81, 81, 81))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel7)
                                .addGap(36, 36, 36)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140,
                                        Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(39, 39, 39))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(297, 297, 297)
                                .addComponent(jLabel6)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel1)
                                .addGap(202, 202, 202)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addGap(93, 93, 93)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel6)
                                .addGap(128, 128, 128)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12))
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1)
                                        .addComponent(jButton2))
                                .addGap(16, 16, 16)));

        pack();
    }// </editor-fold>

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
        // Vacío
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        String eventoSeleccionado = jComboBox1.getSelectedItem().toString();
        Evento eventoActual = null;

        if (eventoSeleccionado.equals("Bts Arirang")) {
            eventoActual = btsArirang;
        } else if (eventoSeleccionado.equals("Humbe Esencia Tour")) {
            eventoActual = humbeTour;
        } else if (eventoSeleccionado.equals("Megaland")) {
            eventoActual = megaland;
        }

        if (eventoActual != null) {
            if (cajero == null) {
                Banco bancoPrueba = new Banco("Banco Demo");
                Cliente ana = new Cliente("Ana Perez", "1001");
                bancoPrueba.agregarCliente(ana);
                Cuenta cuentaPrueba = new Cuenta("C001", ana, 500000, 400000);
                cuentaPrueba.asignarTarjeta(new Tarjeta("1111", "1234"));
                bancoPrueba.agregarCuenta(cuentaPrueba);
                cajero = new Cajeroautomatico(bancoPrueba, 2000000);
            }

            Cuenta cuentaActual = cajero.buscarCuentaPorTarjeta(numeroTarjeta);

            if (cuentaActual != null) {
                Operacionretiro operacionCompra = new Operacionretiro(eventoActual.getTarifa());
                mensaje = operacionCompra.ejecutar(cuentaActual);

            
            } else {
                String mensajeError = "Error: Cuenta no encontrada para la tarjeta " + numeroTarjeta;
                java.awt.EventQueue.invokeLater(() -> new JPaneErrores(mensajeError).setVisible(true));
                dispose();
            }
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        java.awt.EventQueue.invokeLater(() -> new VistaMenu(cajero, numeroTarjeta).setVisible(true));
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        // Configuración de prueba idéntica a las otras vistas para que encuentre la
        // cuenta
        Banco bancoPrueba = new Banco("Banco Demo");
        Cliente ana = new Cliente("Ana Perez", "1001");
        bancoPrueba.agregarCliente(ana);
        Cuenta cuentaPrueba = new Cuenta("C001", ana, 500000, 400000);
        cuentaPrueba.asignarTarjeta(new Tarjeta("1111", "1234"));
        bancoPrueba.agregarCuenta(cuentaPrueba);
        Cajeroautomatico cajeroPrueba = new Cajeroautomatico(bancoPrueba, 2000000);

        java.awt.EventQueue.invokeLater(() -> new VistaBoletas(cajeroPrueba, "1111").setVisible(true));
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration
}
